slurm_config: big
task_type: local_predict
dataset:
  split: test
  video_processor: VideoProcessor
  aligner: COINActionSegmentationAligner
  bert_name: bert-base-uncased
  train_path: data/crosstask/crosstask_release/videos.csv
  train_csv_path: data/crosstask/crosstask_release/videos.csv
  val_path: data/crosstask/crosstask_release/videos_val.csv
  val_csv_path: data/crosstask/crosstask_release/videos_val.csv
  primary_path: data/crosstask/crosstask_release/tasks_primary.txt
  related_path: data/crosstask/crosstask_release/tasks_related.txt
  annotation_path: data/crosstask/crosstask_release/annotations
  meta_processor: CrossTaskActionSegmentationMetaProcessor
  vfeat_dir: data/feat/feat_crosstask_s3d
  text_processor: COINActionSegmentationTextProcessor
  num_iso_layer: 12
  sliding_window: 16
  sliding_window_size: 32
  max_video_len: 32
  max_len: 96
fairseq:
  dataset:
    batch_size: 1
    valid_subset: test
    num_workers: 2
  common_eval:
    path: runs/retri/videoclip/crosstask_segmentation/checkpoint_best.pt
model:
  model_cls: MMFusionSeparateActionSegmentation
  mm_encoder_cls: null
  video_encoder_cls: MMBertForTokenClassification
  text_encoder_cls: BertModel
  num_hidden_video_layers: 6
eval:
  save_path: runs/retri/videoclip/crosstask_segmentation/eval
metric: COINActionSegmentationMetric
predictor: COINPredictor
